export enum CustomerOperationStatus {
    SUCCESS="SUCCESS",
    INVALID_PASSWORD="INVALID_PASSWORD",
    PHONE_NUMBER_UNVERIFIED ="PHONE_NUMBER_UNVERIFIED",
    PHONE_NUMBER_ALREADY_VERIFIED="PHONE_NUMBER_UNVERIFIED",
    INVALID_OTP="INVALID_OTP",
    OTP_EXPIRED="OTP_EXPIRED"
}
